Prepare all required actions Run ./.github/actions/deploy-service Run if git diff --quiet HEAD^ HEAD -- services/servico_ofertas; then No changes detected in services/servico_ofertas. Skipping deployment. 0s Prepare all required actions Run ./.github/actions/deploy-service   with:     service_path: services/servico-produtos     vercel_project_name: servico-produtos     vercel_org_id: ***     vercel_token: *** Run if git diff --quiet HEAD^ HEAD -- services/servico-produtos; then   if git diff --quiet HEAD^ HEAD -- services/servico-produtos; then     echo "No changes detected in services/servico-produtos. Skipping deployment."     echo "should_deploy=false" >> $GITHUB_OUTPUT   else     echo "Changes detected in services/servico-produtos. Proceeding with deployment."     echo "should_deploy=true" >> $GITHUB_OUTPUT   fi   shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0} Changes detected in services/servico-produtos. Proceeding with deployment. Run echo "Navigating to services/servico-produtos"   echo "Navigating to services/servico-produtos"   cd services/servico-produtos
  echo "Running Vercel deploy for servico-produtos..."
  # Redirect output to a temporary file
  TEMP_OUTPUT_FILE=$(mktemp)
  vercel deploy --prebuilt --prod --token *** --scope *** --project servico-produtos --confirm > "$TEMP_OUTPUT_FILE" 2>&1
  DEPLOY_EXIT_CODE=$?

  echo "--- Vercel Deploy Output ---"
  cat "$TEMP_OUTPUT_FILE"
  echo "----------------------------"

  # Clean up temporary file
  rm "$TEMP_OUTPUT_FILE"

  # Check the exit code of the vercel deploy command
  if [ "$DEPLOY_EXIT_CODE" -ne 0 ]; then
    echo "Erro: O comando 'vercel deploy' falhou com código de saída $DEPLOY_EXIT_CODE. Verifique a saída acima para detalhes."
    exit 1
  fi

  # Extrai a URL do deploy da saída
  DEPLOY_URL=$(cat "$TEMP_OUTPUT_FILE" | grep -o 'https://[a-zA-Z0-9.-]*\.vercel\.app' | tail -n 1)

  if [ -z "$DEPLOY_URL" ]; then
    echo "Erro: O comando 'vercel deploy' foi bem-sucedido, mas não foi possível extrair a URL de deploy da saída da Vercel." # ou o deploy falhou e não gerou URL
    exit 1
  fi

  echo "Deployed URL: $DEPLOY_URL"
  echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    VERCEL_ORG_ID: ***
    VERCEL_PROJECT_ID: servico-produtos
    VERCEL_TOKEN: ***
Navigating to services/servico-produtos
Running Vercel deploy for servico-produtos...
Error: Process completed with exit code 1.
0s
1s