deploy-microservices failed now in 18s Search logs 0s 1s 14s 0s 0s 0s 0s 0s 0s Prepare all required actions Run ./.github/actions/deploy-service   with:     service_path: services/servico_ofertas     vercel_project_name: servicoofertas     vercel_org_id: ***     vercel_token: *** Run if git diff --quiet HEAD^ HEAD -- services/servico_ofertas; then   if git diff --quiet HEAD^ HEAD -- services/servico_ofertas; then     echo "No changes detected in services/servico_ofertas. Skipping deployment."     echo "should_deploy=false" >> $GITHUB_OUTPUT   else     echo "Changes detected in services/servico_ofertas. Proceeding with deployment."     echo "should_deploy=true" >> $GITHUB_OUTPUT   fi   shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0} No changes detected in services/servico_ofertas. Skipping deployment. 1s Prepare all required actions Run ./.github/actions/deploy-service   with:     service_path: services/servico-produtos     vercel_project_name: servico-produtos     vercel_org_id: ***     vercel_token: *** Run if git diff --quiet HEAD^ HEAD -- services/servico-produtos; then   if git diff --quiet HEAD^ HEAD -- services/servico-produtos; then     echo "No changes detected in services/servico-produtos. Skipping deployment."     echo "should_deploy=false" >> $GITHUB_OUTPUT   else     echo "Changes detected in services/servico-produtos. Proceeding with deployment."     echo "should_deploy=true" >> $GITHUB_OUTPUT   fi   shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0} Changes detected in services/servico-produtos. Proceeding with deployment. Run echo "Navigating to services/servico-produtos"   echo "Navigating to services/servico-produtos"   cd services/servico-produtos
  echo "Running Vercel deploy for servico-produtos..."
  DEPLOY_OUTPUT=$(vercel deploy --prebuilt --prod --token *** --scope *** --project servico-produtos --confirm 2>&1)

  echo "$DEPLOY_OUTPUT"

  # Extrai a URL do deploy da saída
  DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[a-zA-Z0-9.-]*\.vercel\.app' | tail -n 1)

  if [ -z "$DEPLOY_URL" ]; then
    echo "Erro: Não foi possível extrair a URL de deploy da saída da Vercel."
    exit 1
  fi

  echo "Deployed URL: $DEPLOY_URL"
  echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    VERCEL_ORG_ID: ***
    VERCEL_PROJECT_ID: servico-produtos
    VERCEL_TOKEN: ***
Navigating to services/servico-produtos
Running Vercel deploy for servico-produtos...
Error: Process completed with exit code 1.